AllCops:
  NewCops: enable
  TargetRubyVersion: 3.0
  Exclude:
  - 'vendor/**/*'
  - 'ext/**/*'
  - '*.gemspec'

Layout/LineLength:
  Max: 120

Style/Documentation:
  Enabled: false

Metrics/AbcSize:
  Max: 40

Metrics/CyclomaticComplexity:
  Max: 20

Metrics/MethodLength:
  Max: 100

Metrics/PerceivedComplexity:
  Max: 20

Metrics/ClassLength:
  Max: 200

Layout/FirstArrayElementIndentation:
  EnforcedStyle: consistent
