name: Test Ruby

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0'
          bundler-cache: true

      - name: Setup Tapioca cache
        id: cache-tapioca
        uses: actions/cache@v5
        with:
          path: sorbet
          key: ${{ runner.os }}-${{ hashFiles('Gemfile.lock') }}

      - name: Init Tapioca
        if: steps.cache-tapioca.outputs.cache-hit != 'true'
        run: |
          bundle exec tapioca init && \
          bundle exec srb rbi suggest-typed

      - name: Run rubocop
        run: bundle exec rubocop --parallel

      # - name: Build native part
      #   run: |
      #     bundle exec rake generate && \
      #     bundle exec rake compile

      - name: Build native part
        run: |
          bundle exec rake compile

      - name: Run typecheck
        run: |
          bundle exec srb typecheck -q

      - name: Run tests
        run: bundle exec rake test
